# Generated by Django 4.2.15 on 2024-08-29 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0002_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='health_issue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lifestyle_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines_prescribed',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptoms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
